namespace EventExample;

class Shared
{
    public static int[] Data { get; set; }//Store data values generated by producer thread
    public static int DataCount { get; set; }//Total number of values
    public static ManualResetEvent Event{ get; set; }

    static Shared()
    {
        Data = new int[15];
        DataCount = Data.Length;
        Event = new ManualResetEvent(false);//unsignaled (false)
    }
}

//Represents producer thread
class Producer
{
    public void Produce()
    {
        System.Console.WriteLine($"{Thread.CurrentThread.Name} started.");
        //Generate some data and store it in the Data array
        for (int i = 0; i < Shared.Data.Length; i++)
        {
            Shared.Data[i] = i + 1;
            Thread.Sleep(300);//simular artificial latency (delay)
        }

        //Set the signal (signal that the producer has finished generating data)
        Shared.Event.Set();
        System.Console.WriteLine($"{Thread.CurrentThread.Name} finished.");
    }
}

//Represents consumer thread
class Consumer
{
    public void Consume()
    {
        System.Console.WriteLine($"{Thread.CurrentThread.Name} started.");
        System.Console.WriteLine($"{Thread.CurrentThread.Name} is waiting for Producer Thread to finish generating data");

        Shared.Event.WaitOne();//consumer thread waits until the status of event becomes signaled

       System.Console.WriteLine($"{Thread.CurrentThread.Name} has received a signal from the Producer Thread");
        //raad data
        System.Console.WriteLine("\nData is: ");
        for (int i = 0; i < Shared.Data.Length; i++)
        {
            System.Console.WriteLine(Shared.Data[i]);
        }
        
        System.Console.WriteLine($"{Thread.CurrentThread.Name} finished.");
    }
}

class Program
{
    static void Main(string[] args)
    {
        System.Console.WriteLine("Main thread started.");
        
        // Create Producer and Consumer objects
        Producer producer = new Producer();
        Consumer consumer = new Consumer();

        //Create delegate objects of ThreadStart type
        ThreadStart producerThreadStart = new ThreadStart(producer.Produce);
        ThreadStart consumerThreadStart = new ThreadStart(consumer.Consume);

        //Create Producer and Consumer threads
        Thread producerThread = new Thread(producerThreadStart);
        Thread consumerThread = new Thread(consumerThreadStart);

        //Set thread names
        producerThread.Name = "Producer Thread";
        consumerThread.Name = "Consumer Thread";

        //Start threads
        producerThread.Start();
        consumerThread.Start();

        //Wait for threads to finish
        producerThread.Join();
        consumerThread.Join();

        System.Console.WriteLine("Main thread finished.");
    }
}
