namespace EventExample;

class Shared
{
    public static int[] Data { get; set; }//Store data values generated by producer thread
    public static int BatchCount { get; set; }//Total number of values
    public static int BatchSize { get; set; }
    public static AutoResetEvent Event{ get; set; }

    static Shared()
    {
        Data = new int[15];
        BatchCount = 5;
        BatchSize = 3;
        Event = new AutoResetEvent(false);//unsignaled (false)
    }
}

//Represents producer thread
class Producer
{
    public void Produce()
    {
        System.Console.WriteLine($"{Thread.CurrentThread.Name} started.");
        //Generate some data and store it in the Data array
        for (int i = 0; i < Shared.BatchCount; i++)//5
        {
            for (int j = 0; j < Shared.BatchSize; j++)//3
            {
                Shared.Data[i*Shared.BatchSize+j] = (i*Shared.BatchSize)+j + 1;//1 to 15
                Thread.Sleep(500);//simular artificial latency (delay)
            }
             //Set the signal (signal that the producer has finished generating data)
            Shared.Event.Set();

            //reset the event to unsignaled state for next batch
            //Shared.Event.Reset();
        }

        System.Console.WriteLine($"{Thread.CurrentThread.Name} finished.");
    }
}

//Represents consumer thread
class Consumer
{
    public void Consume()
    {
        System.Console.WriteLine($"{Thread.CurrentThread.Name} started.");
        System.Console.WriteLine($"{Thread.CurrentThread.Name} is waiting for Producer Thread to finish generating data");
        for (int i = 0; i < Shared.BatchCount; i++)//5
        {
            //block consumer thread until signaled
            Shared.Event.WaitOne();

            //Consume the data generated by the producer thread
            System.Console.WriteLine($"{Thread.CurrentThread.Name} consumed data batch {i + 1}:");
            for (int j = 0; j < Shared.BatchSize; j++)//3
            {
                System.Console.Write(Shared.Data[i * Shared.BatchSize + j] + " ");
                Thread.Sleep(200);//simular artificial latency (delay)
            }
            System.Console.WriteLine();
        }
        
        System.Console.WriteLine($"{Thread.CurrentThread.Name} finished.");
    }
}

class Program
{
    static void Main(string[] args)
    {
        System.Console.WriteLine("Main thread started.");
        
        // Create Producer and Consumer objects
        Producer producer = new Producer();
        Consumer consumer = new Consumer();

        //Create delegate objects of ThreadStart type
        ThreadStart producerThreadStart = new ThreadStart(producer.Produce);
        ThreadStart consumerThreadStart = new ThreadStart(consumer.Consume);

        //Create Producer and Consumer threads
        Thread producerThread = new Thread(producerThreadStart);
        Thread consumerThread = new Thread(consumerThreadStart);

        //Set thread names
        producerThread.Name = "Producer Thread";
        consumerThread.Name = "Consumer Thread";

        //Start threads
        producerThread.Start();
        consumerThread.Start();

        //Wait for threads to finish
        producerThread.Join();
        consumerThread.Join();

        System.Console.WriteLine("Main thread finished.");
    }
}
